keys:
  # USB A v5 yubikeys
  - &nano age1vqnguqjqxpjckft5gjlt2m4lzdhh8ymzwycha9cahqnj6ygjc4ms855jds
  - &portable age1a0a4av92pa3ld4mwqpg2g72csxhxau4hw96860d5zvlzldq0aemsdn9lwd
  - &backup age105nux02frp73gs98f9j5dec3dae6608xsr58atzhxresc7p72e7sakds6z
  # plain Age key (not FIDO backed). Will eventually go away.
  - &plain age1vpv9a94wj6p0tkngymfsysnzam20fkrjd3zs3trzfatzpqz42ayqpp2amc
  # One iteration of my test VM.
  - &qemu age163377n4x95khq0tvmlddpz2ykxq4wmxtcf0cel4vsassfkaug9qsntyv88
  - &bistannix age1efmhh99fn52a9w0yszfdxupz93lr77ewag2cd6n5l5jfhgp6z3hs8ck48g
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *nano
          - *portable
          - *backup
          - *plain
          - *qemu
          - *bistannix
