# Recall: `mkdocs serve` in the top-level directory gives you a local
# version.
site_name: Nicolas and NixOS
site_url: https://nicdumz.fr/nix-config
site_author: Nicolas Dumazet
copyright: Copyright &copy; 2025 Nicolas Dumazet
repo_name: nicdumz/nix-config
repo_url: https://github.com/nicdumz/nix-config
edit_uri: edit/main/docs/
theme:
  name: material
  # Default themes, but support automatic dark theme.
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - header.autohide
    - content.action.edit # edit in Github links
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.footer # link to next page
    - navigation.tracking
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: simple/git
    logo: simple/nixos
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.critic
nav:
  - The journey: index.md
  - Model: model.md
  - Requirements: requirements.md
  - Solution: solution.md
  - Details: details.md
  - Conclusion: conclusion.md
extra:
  analytics:
    provider: google
    property: G-FT3XEHJ2DX
