http:
  routers:
    traefik:
      rule: "Host(`traefik.home.nicdumz.fr`)"
      service: api@internal
      middlewares:
        - allowlist
  middlewares:
    allowlist:
      ipAllowList:
        sourceRange:
          - "192.168.1.1/24"
          - "127.0.0.1"
          - "100.70.128.5"
          - "100.99.40.65"
    cors:
      headers:
        accessControlAllowMethods:
          - GET
          - HEAD
          - OPTIONS
          - PUT
        accessControlAllowCredentials: true
        accessControlAllowOriginList: ["https://jellyseerr.home.nicdumz.fr/", "https://home.nicdumz.fr"]
        addVaryHeader: true
tls:
  stores:
    default:
      defaultGeneratedCert:
        resolver: gandi
        domain:
          main: "*.home.nicdumz.fr"
          sans:
            - "home.nicdumz.fr"
