modules:
  http_2xx_v4:
    prober: http
    http:
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
  http_2xx_v6:
    prober: http
    http:
      preferred_ip_protocol: "ip6"
      ip_protocol_fallback: false
