api:
  dashboard: true
  debug: false
ping: {}
metrics:
  prometheus:
    addEntryPointsLabels: true
providers:
  docker:
    # exposedByDefault: true # this is the default
    # endpoint: # overriden in derivation
    defaultRule: "Host(`{{ .ContainerName }}.home.nicdumz.fr`)"
entryPoints:
  websecure:
    address: "somehost:443" # also overriden in derivation
    http:
      middlewares:
        - cors@file
      tls:
        certResolver: gandi
# Verbose traffic log so I can debug
accessLog: {}
certificatesResolvers:
  gandi:
    acme:
      email: "nicdumz@gmail.com"
      storage: "/var/lib/traefik/acme.json"
      dnsChallenge:
        provider: gandiv5
