name: "Docs: Release to GitHub pages"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docs-release.yaml"
      - "mkdocs.yml"
      - "docs/**"
      - "wrangler.jsonc"
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      # Wrangler action uses wrangler 3.x, this is a workaround to use current 4.x
      # See https://github.com/cloudflare/wrangler-action/issues/390
      - name: Install Wrangler v4
        run: npm install --save-dev wrangler@4
      - run: "echo \"cache_id=$(date --utc '+%V')\" >> \"$GITHUB_ENV\""
      - uses: actions/cache@v5
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-
      - name: Install mkdocs
        run: pip install mkdocs-material
      - name: Local website build
        run: mkdocs build
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
